config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events, only: [:new, :create, :index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true

  belongs_to :creator, class_name: 'User'
  
  has_many :attendees, through: :event_attendances, source: :event_attendee
  has_many :event_attendances, foreign_key: :attended_event_id
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :event_attendee_id, class_name: 'User'
  belongs_to :attended_event_id, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  
  has_many :attended_events, through: :event_attendances
  has_many :event_attendances, foreign_key: :event_attendee_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttedancesController < ApplicationController

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :date, :location, :creator_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h1>WELCOME</h1>
<h2>EVENTS</h2>

<% @events.each do |evt| %>
  <ul>
    <li>
      <%= link_to evt.name, event_path(evt) %>
    </li>
  </ul>
<% end %>

<% if user_signed_in?  %>
  <%= link_to 'Create Event', new_event_path %><br>
  <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <%= form.label :name, 'Event Name:' %>
  <%= form.text_field :name %><br><br>
  <%= form.label :date, 'Date:' %>
  <%= form.date_field :date %><br><br>
  <%= form.label :location, 'Location:' %>
  <%= form.text_field :location %><br><br>
  <%= form.submit 'Submit' %>
<% end %>

<br>
<%= link_to "Home page", root_path %>

app/views/events/show.html.erb
<h1>Event Details</h1>

<%= @event.name %><br>
Date: <%= @event.date %><br>
Location: <%= @event.location %>

<br><br>
<%= link_to "Home page", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% @user.events.each do |evt| %>
  <ul>
    <li><%= evt.name %></li>
  </ul>
<% end %>